### ISSUE TITLE
Missing key min_cert_id in group_update_domain task results

### ISSUE THREAD

**Issue by felddy** [cisagov/admiral#1]
# 💥 Regression Report

The `min_cert_id` is no longer present in the response from the `group_update_domain` task.

## Last working version

Version didn't change

Worked up to date: 20200103 (last run)
Stopped working on date:  20200111 (today)

## To Reproduce

- Run the `examples/load_certs.py` as normal

## Expected behavior

Certificates are loaded as usual.

## Any helpful log output

Paste the results here:

```python
Traceback (most recent call last):                                                                                          
  File "./load_certs.py", line 193, in <module>
    main()
  File "./load_certs.py", line 177, in main
    total_new_count += load_certs(domains, args["--skipto"], args["--verbose"])
  File "./load_certs.py", line 152, in load_certs
    new_count = group_update_domain(domain, EARLIEST_EXPIRED_DATE, verbose)
  File "./load_certs.py", line 105, in group_update_domain
    for log_id in get_new_log_ids(domain.domain, max_expired_date, verbose):
  File "./load_certs.py", line 67, in get_new_log_ids
    log_id = i["min_cert_id"]
KeyError: 'min_cert_id'
```

**Comment by felddy** [comment]
The field `min_cert_id` was renamed to `id`.
